version: '3.9'

services:
  redis:
    image: redis:6.2.0-alpine
    ports:
      - 9500:6379

  service:
    build: .
    ports:
      - 3000:3000
    env_file: .env
    environment:
      PORT: 3000
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis
