version: '3.9'

services:
  database:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_USER: user_service
      POSTGRES_PASSWORD: user_service
      POSTGRES_DB: user_service
    ports:
      - 9001:5432

  service:
    build: .
    ports:
      - 3001:3000
    env_file: .env
    environment:
      PORT: 3000
      DATABASE_HOST: database
      DATABASE_PORT: 5432
    depends_on:
      - database
