version: '3.9'

services:
  user_database:
    image: postgres:13.1-alpine
    environment:
      POSTGRES_USER: user_service
      POSTGRES_PASSWORD: user_service
      POSTGRES_DB: user_service
    ports:
      - 9001:5432

  user_service:
    build: .
    ports:
      - 3001:3000
    env_file: .env
    environment:
      PORT: 3000
      DATABASE_HOST: user_database
      DATABASE_PORT: 5432
    depends_on:
      - user_database
