version: '3.9'

services:
  database:
    image: postgres:13.1-alpine
    environment:
      POSTGRES_USER: user_service
      POSTGRES_PASSWORD: user_service
      POSTGRES_DB: user_service
    ports:
      - 9001:5432
