version: '3.9'

services:
  # redis:
  #   image: redis:6.0.9-alpine

  database:
    image: postgres:13.1-alpine
    environment:
      POSTGRES_USER: authentication_service
      POSTGRES_PASSWORD: authentication_service
      POSTGRES_DB: authentication_service
    ports:
      - 9000:5432
