version: '3.9'

services:
  database:
    image: postgres:13.2-alpine
    environment:
      POSTGRES_USER: authentication_service
      POSTGRES_PASSWORD: authentication_service
      POSTGRES_DB: authentication_service
    ports:
      - 9000:5432

  authentication_service:
    build: .
    ports:
      - 3003:3000
    env_file: .env
    environment:
      PORT: 3000
      DATABASE_HOST: database
      DATABASE_PORT: 5432
    depends_on:
      - database
