version: '3.9'

services:
  database:
    image: postgres:13.2-alpine
    environment:
      POSTGRES_USER: boilerplate_service
      POSTGRES_PASSWORD: boilerplate_service
      POSTGRES_DB: boilerplate_service
    ports:
      - 5432:5432

  service:
    build: .
    ports:
      - 3000:3000
    env_file: .env
    environment:
      PORT: 3000
      DATABASE_HOST: database
      DATABASE_PORT: 5432
    depends_on:
      - database
