version: '3.9'

services:
  boilerplate_database:
    image: postgres:13.1-alpine
    environment:
      POSTGRES_USER: boilerplate_service
      POSTGRES_PASSWORD: boilerplate_service
      POSTGRES_DB: boilerplate_service
    ports:
      - 5432:5432

  boilerplate_service:
    build: .
    ports:
      - 3000:3000
    env_file: .env
    environment:
      PORT: 3000
      DATABASE_HOST: boilerplate_database
      DATABASE_PORT: 5432
    depends_on:
      - boilerplate_database
