name: build_email

on:
  push:
    paths:
    - 'services/email/**'
    - '.github/workflows/build_email.yml'

defaults:
  run:
    working-directory: services/email

jobs:

  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # - name: Cache node_modules
    #   id: cache
    #   uses: actions/cache@v2
    #   with:
    #     path: node_modules
    #     key: node-${{ hashFiles('package-lock.json', '.nvmrc') }}

    # - run: npm ci
    #   if: github.event.inputs.useCache == 'no' || steps.cache.outputs.cache-hit == 'false'

    - name: ESLint
      run: eslint .

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build container image
      uses: docker/build-push-action@v2
      with:
        context: .
        tags: email:latest
        load: true

    - name: Install grype
      run: curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b .

    # - name: Run docker scan with Snyk
    #   run: docker scan --accept-license email:latest

    - name: Run grype
      run: ./grype --fail-on medium email:latest
