name: build_email

on:
  push:
    paths:
    - 'services/email/**'

jobs:

  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build container image
      uses: docker/build-push-action@v2
      with:
        context: services/email
        tags: email:latest
        load: true

    - name: Scan container image
      uses: anchore/scan-action@v2
      id: scan
      with:
        image: "email:latest"
        acs-report-enable: true

    - name: grype scan JSON results
      run: for j in `ls ./anchore-reports/*.json`; do echo "---- ${j} ----"; cat ${j}; echo; done
